import { createPrivateKey, sign } from "node:crypto";
import { readFile } from "node:fs/promises";
import type { AscOperation, AscPlan, ShipLayerManifest } from "./types.js";

const API_ROOT = "https://api.appstoreconnect.apple.com/v1";
export interface FetchResponse { ok: boolean; status: number; text(): Promise<string> }
export type FetchLike = (input: string, init?: RequestInit) => Promise<FetchResponse>;
export interface AscCredentials { issuerId: string; keyId: string; privateKeyPath: string }
export interface RemoteDiscovery { appId?: string; app?: unknown; appInfos: unknown[]; appInfoLocalizations: unknown[]; versions: unknown[]; versionLocalizations: unknown[]; builds: unknown[]; reviewDetails: unknown[]; screenshots: unknown[]; inAppPurchases: unknown[]; subscriptionGroups: unknown[] }

export function credentialsFromEnvironment(manifest: ShipLayerManifest, environment: NodeJS.ProcessEnv = process.env): AscCredentials | undefined { const keyId = manifest.sync.appStoreConnectKeyIdEnv ? environment[manifest.sync.appStoreConnectKeyIdEnv] : undefined; const issuerId = manifest.sync.issuerIdEnv ? environment[manifest.sync.issuerIdEnv] : undefined; const privateKeyPath = manifest.sync.privateKeyPathEnv ? environment[manifest.sync.privateKeyPathEnv] : undefined; return keyId && issuerId && privateKeyPath ? { keyId, issuerId, privateKeyPath } : undefined; }
export async function createJwt(credentials: AscCredentials, now = new Date()): Promise<string> { const header = base64url({ alg: "ES256", kid: credentials.keyId, typ: "JWT" }); const payload = base64url({ iss: credentials.issuerId, aud: "appstoreconnect-v1", exp: Math.floor(now.getTime() / 1000) + 1_000 }); const signingInput = `${header}.${payload}`; const key = createPrivateKey(await readFile(credentials.privateKeyPath, "utf8")); const signature = sign("sha256", Buffer.from(signingInput), { key, dsaEncoding: "ieee-p1363" }); return `${signingInput}.${signature.toString("base64url")}`; }
export class AppStoreConnectClient {
  constructor(private readonly credentials: AscCredentials, private readonly fetcher: FetchLike = fetch as unknown as FetchLike) {}
  async get(path: string): Promise<unknown> { const token = await createJwt(this.credentials); const response = await this.fetcher(`${API_ROOT}${path}`, { headers: { Authorization: `Bearer ${token}`, Accept: "application/json" } }); const body = await response.text(); if (!response.ok) throw new Error(`App Store Connect read failed (${response.status}): ${redact(body)}`); return body ? JSON.parse(body) : {}; }
  async discover(bundleId: string): Promise<RemoteDiscovery> { const appResponse = await this.get(`/apps?filter[bundleId]=${encodeURIComponent(bundleId)}&limit=1`) as { data?: Array<{ id: string }> }; const appId = appResponse.data?.[0]?.id; if (!appId) return emptyDiscovery(); const [appInfosResponse, versionsResponse, builds, inAppPurchases, subscriptionGroups] = await Promise.all([this.get(`/apps/${appId}/appInfos?limit=200`), this.get(`/apps/${appId}/appStoreVersions?limit=200`), this.get(`/apps/${appId}/builds?limit=200`), this.get(`/apps/${appId}/inAppPurchasesV2?limit=200`), this.get(`/apps/${appId}/subscriptionGroups?limit=200`)]); const appInfos = dataOf(appInfosResponse); const versions = dataOf(versionsResponse); const appInfoId = idOf(appInfos[0]); const versionId = idOf(versions[0]); const [appInfoLocalizations, versionLocalizations, reviewDetails, screenshots] = await Promise.all([appInfoId ? this.get(`/appInfos/${appInfoId}/appInfoLocalizations?limit=200`).then(dataOf) : Promise.resolve([]), versionId ? this.get(`/appStoreVersions/${versionId}/appStoreVersionLocalizations?limit=200`).then(dataOf) : Promise.resolve([]), versionId ? this.get(`/appStoreVersions/${versionId}/appStoreVersionAppReviewDetail`).then(dataOf) : Promise.resolve([]), versionId ? this.get(`/appStoreVersions/${versionId}/appScreenshotSets?include=appScreenshots&limit=200`).then(dataOf) : Promise.resolve([])]); return { appId, app: appResponse.data?.[0], appInfos, appInfoLocalizations, versions, versionLocalizations, builds: dataOf(builds), reviewDetails, screenshots, inAppPurchases: dataOf(inAppPurchases), subscriptionGroups: dataOf(subscriptionGroups) }; }
}
function dataOf(value: unknown): unknown[] { return Array.isArray((value as { data?: unknown[] }).data) ? (value as { data: unknown[] }).data : []; }
function idOf(value: unknown): string | undefined { return typeof (value as { id?: unknown })?.id === "string" ? (value as { id: string }).id : undefined; }
function emptyDiscovery(): RemoteDiscovery { return { appInfos: [], appInfoLocalizations: [], versions: [], versionLocalizations: [], builds: [], reviewDetails: [], screenshots: [], inAppPurchases: [], subscriptionGroups: [] }; }
function base64url(value: object): string { return Buffer.from(JSON.stringify(value)).toString("base64url"); }
function redact(input: string): string { return input.replace(/-----BEGIN[^-]+-----[\s\S]*?-----END[^-]+-----/g, "[REDACTED KEY]").slice(0, 600); }

export async function appStorePlan(manifest: ShipLayerManifest, remote = false, environment: NodeJS.ProcessEnv = process.env, fetcher?: FetchLike): Promise<AscPlan> {
  const operations = baseOperations(manifest); const credentials = credentialsFromEnvironment(manifest, environment);
  if (!remote) return { mode: "offline", operations, credentialsPresent: Boolean(credentials), warnings: ["Offline dry-run: no App Store Connect request was made.", "Initial app record creation, agreements, banking/tax/trader declarations, privacy/legal confirmation, and final submission are human-controlled."] };
  if (!credentials) return { mode: "remote", operations, credentialsPresent: false, warnings: ["Remote discovery was requested but credentials are unavailable. No request was made."] };
  const discovery = await new AppStoreConnectClient(credentials, fetcher).discover(manifest.app.bundleId);
  if (!discovery.appId) operations.unshift({ id: "manual.create-app-record", action: "manual", resource: "Apps", description: "Create the initial app record in App Store Connect UI, then add app.appStoreAppId.", safety: "manual", status: "unsupported" });
  else { for (const operation of operations) if (operation.resource === "App identity") operation.status = "already-matches"; }
  return { mode: "remote", operations, credentialsPresent: true, warnings: [`Remote discovery completed for ${discovery.appId || "no matching app"}. This command performed reads only.`, "ShipLayer v0.1 does not mutate App Store Connect; use the generated plan to perform reviewed UI/API operations."] };
}
function baseOperations(manifest: ShipLayerManifest): AscOperation[] { const operations: AscOperation[] = [ { id: "read.app", action: "read", resource: "App identity", description: `Find app with bundle ID ${manifest.app.bundleId || "MISSING"}.`, safety: "read-only", status: "planned" }, { id: "compare.metadata", action: "update", resource: "App metadata/localizations", description: "Compare generated metadata with App Store Connect before uploading reviewed fields.", safety: "requires-apply", status: "planned" }, { id: "compare.build", action: "read", resource: "Build", description: `Locate build ${manifest.app.build || "MISSING"} for version ${manifest.app.version || "MISSING"}.`, safety: "read-only", status: "planned" }, { id: "upload.screenshots", action: "upload", resource: "Screenshots", description: "Upload only reviewed, Apple-accepted marketing screenshots after reservation/upload/commit/processing validation.", safety: "requires-apply", status: "planned" }, { id: "manual.privacy", action: "manual", resource: "App Privacy", description: "Human confirms privacy answers and all third-party processing in App Store Connect.", safety: "manual", status: "unsupported" }, { id: "submit.final", action: "submit", resource: "Review submission", description: "Select the approved build and submit only after an explicit final command and human confirmation.", safety: "requires-submit", status: "unsupported" } ]; if (manifest.monetization.type === "subscriptions") operations.splice(3, 0, { id: "compare.subscriptions", action: "update", resource: "Subscription group/products", description: "Compare subscription group, products, localizations, offers, price references, paywall navigation, and review assets.", safety: "requires-apply", status: "planned" }); else if (manifest.monetization.type === "non-consumables") operations.splice(3, 0, { id: "compare.iap", action: "update", resource: "In-App Purchases", description: "Compare non-consumable product IDs, localizations, prices, and review assets.", safety: "requires-apply", status: "planned" }); return operations; }
