import path from "node:path";
import { lstat, mkdir, readFile, rename, rm } from "node:fs/promises";
import { stringify } from "yaml";
import { ensureDirectory, resolveContained, safeRelativePath, stableJson, writeText } from "./fs.js";
import type { AnalysisReport, PreflightReport, ShipLayerManifest } from "./types.js";

export interface PreparedPackage { directory: string; files: string[] }
const RESERVED_OUTPUT_ROOTS = new Set([".git", ".shiplayer-staging", "node_modules", "Pods", "Carthage", "DerivedData", "build", ".build", "dist", ".swiftpm", "vendor", "release", "shiplayer.yml"]);
export async function generateReleasePackage(repository: string, manifest: ShipLayerManifest, analysis: AnalysisReport, preflight: PreflightReport, outputDirectory: string): Promise<PreparedPackage> {
  assertManifestPaths(manifest); const outputRelative = safeRelativePath(outputDirectory, "--out"); assertOutputPath(outputRelative); assertOutputDoesNotCollide(manifest, outputRelative); const out = await resolveContained(repository, outputRelative, "--out"); await ensureOutputParent(repository, outputRelative); await assertManagedDestination(out); const stage = await createStage(repository); const files: string[] = []; const emit = async (relativePath: string, contents: string): Promise<void> => { assertNoSecretOutput(contents, relativePath); await writeText(path.join(stage, relativePath), contents); files.push(relativePath); };
  try {
  await emit("manifest.normalized.yml", stringify(manifest, { sortMapEntries: true }));
  // Entry counts include ignored/generated directory entries, which can legitimately
  // change after a prior prepare. Keep the package report reproducible instead of
  // pretending that a runtime traversal counter is stable release metadata.
  const { entriesVisited: _entriesVisited, filesScanned: _filesScanned, filesOverLimit: _filesOverLimit, filesOverLimitPaths: _filesOverLimitPaths, ...packageIgnored } = analysis.ignored;
  const packageAnalysis = { ...analysis, repository: ".", scannedAt: "omitted-for-deterministic-package", ignored: { ...packageIgnored, directories: analysis.ignored.directories.filter((directory) => !/(^|\/)(?:shiplayer-)?release(?:-|$)|(^|\/)\.shiplayer-staging(?:\/|$)/.test(directory)) } };
  const packagePreflight = { ...preflight, repository: "." };
  await emit("reports/analysis.json", stableJson(packageAnalysis)); await emit("reports/preflight.json", stableJson(packagePreflight)); await emit("reports/preflight.md", preflightMarkdown(packagePreflight));
  for (const [locale, copy] of Object.entries(manifest.metadata.localizations)) await emit(`metadata/${locale}.json`, stableJson({ locale, ...copy, characterLimits: { name: 30, subtitle: 30, promotionalText: 170, description: 4000, keywords: 100, whatsNew: 4000 } }));
  await emit("privacy/questionnaire-draft.md", privacyDraft(manifest)); await emit("privacy/evidence-matrix.json", stableJson({ disclaimer: "Draft only. Apple privacy declarations require human confirmation and must include third-party processing.", permissions: manifest.permissions, dataProcessing: manifest.dataProcessing, externalProcessors: manifest.externalProcessors, externalServiceDecisions: manifest.externalServiceDecisions }));
  await emit("compliance/age-rating-and-content-rights.md", complianceDraft(manifest));
  await emit("legal/privacy-policy-draft.html", privacyPage(manifest)); await emit("legal/support-page-draft.html", supportPage(manifest)); await emit("legal/terms-of-use-draft.md", termsOfUseDraft(manifest));
  await emit("review/app-review-notes.md", appReviewNotes(manifest)); await emit("review/physical-device-recording-script.md", recordingScript(manifest));
  await emit("screenshots/capture-plan.json", stableJson(capturePlan(manifest))); await emit("screenshots/marketing-composition-plan.json", stableJson(marketingProject(manifest))); await emit("storekit/checklist.md", storeKitChecklist(manifest));
  await emit("app-store-connect/dry-run-plan.md", dryRunPlan(manifest)); await emit("remaining-human-actions.md", humanActions(analysis, packagePreflight));
    await writeText(path.join(stage, ".shiplayer-managed"), "ShipLayer managed release package v1\n"); files.push(".shiplayer-managed"); await installStage(stage, out); return { directory: out, files: files.sort() };
  } catch (error) {
    await rm(stage, { recursive: true, force: true }).catch(() => undefined);
    throw error;
  }
}
function assertOutputPath(outputRelative: string): void { const reserved = outputRelative.split("/").find((component) => RESERVED_OUTPUT_ROOTS.has(component) || component === "shiplayer-release"); if (reserved) throw new Error(`--out cannot use reserved or source-control path '${reserved}'. Use a separate managed release directory.`); }
function assertOutputDoesNotCollide(manifest: ShipLayerManifest, outputRelative: string): void {
  const inputs = ["shiplayer.yml", manifest.screenshots.rawOutputDir, manifest.screenshots.marketingProjectPath, ...(manifest.monetization.type === "subscriptions" || manifest.monetization.type === "non-consumables" ? manifest.monetization.products.map((product) => product.reviewScreenshot) : [])].filter((item): item is string => Boolean(item)).map((item) => safeRelativePath(item, "manifest input"));
  if (inputs.some((input) => outputRelative === input || outputRelative.startsWith(`${input}/`) || input.startsWith(`${outputRelative}/`))) throw new Error("--out collides with a manifest source input. Choose a separate managed release directory.");
}
async function createStage(repository: string): Promise<string> {
  const root = await resolveContained(repository, ".shiplayer-staging", "staging directory");
  try { if ((await lstat(root)).isSymbolicLink()) throw new Error("staging directory cannot be a symlink."); }
  catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
  await mkdir(root, { recursive: true, mode: 0o700 });
  if ((await lstat(root)).isSymbolicLink()) throw new Error("staging directory cannot be a symlink.");
  const stage = path.join(root, `package-${process.pid}-${Date.now()}`); await mkdir(stage, { mode: 0o700 }); return stage;
}
async function ensureOutputParent(repository: string, outputRelative: string): Promise<void> {
  const parentRelative = path.posix.dirname(outputRelative); if (parentRelative === ".") return;
  const parent = await resolveContained(repository, parentRelative, "--out parent directory"); await mkdir(parent, { recursive: true, mode: 0o700 });
  if ((await lstat(parent)).isSymbolicLink()) throw new Error("--out parent directory cannot be a symlink.");
}
async function assertManagedDestination(destination: string): Promise<void> { let details; try { details = await lstat(destination); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return; throw error; } if (details.isSymbolicLink()) throw new Error("--out cannot be a symlink."); if (!details.isDirectory()) throw new Error("--out exists but is not a directory."); const marker = path.join(destination, ".shiplayer-managed"); let markerInfo; try { markerInfo = await lstat(marker); } catch { throw new Error("--out is not a ShipLayer-managed package; refusing to overwrite unrelated files."); } if (markerInfo.isSymbolicLink()) throw new Error("Managed output marker cannot be a symlink."); if (!(await readFile(marker, "utf8")).startsWith("ShipLayer managed release package v1")) throw new Error("--out is not a ShipLayer-managed package; refusing to overwrite unrelated files."); }
async function installStage(stage: string, destination: string): Promise<void> {
  let exists = true; try { await lstat(destination); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") exists = false; else throw error; }
  if (!exists) { await rename(stage, destination); return; }
  const backup = path.join(path.dirname(destination), `.${path.basename(destination)}.shiplayer-backup-${process.pid}-${Date.now()}`);
  try {
    await rename(destination, backup);
    try { await rename(stage, destination); }
    catch (error) { await rename(backup, destination).catch(() => undefined); throw error; }
    await rm(backup, { recursive: true, force: true, maxRetries: 2 });
  } catch (error) { throw error; }
}
function assertManifestPaths(manifest: ShipLayerManifest): void { safeRelativePath(manifest.screenshots.rawOutputDir, "screenshots.rawOutputDir"); if (manifest.screenshots.marketingProjectPath) safeRelativePath(manifest.screenshots.marketingProjectPath, "screenshots.marketingProjectPath"); if (manifest.monetization.type === "non-consumables" || manifest.monetization.type === "subscriptions") for (const product of manifest.monetization.products) safeRelativePath(product.reviewScreenshot, `review screenshot for ${product.productId}`); }
function assertNoSecretOutput(contents: string, label: string): void { if (/-----BEGIN(?: [A-Z]+)? PRIVATE KEY-----/i.test(contents) || /\b(?:api[ _-]?key|access[ _-]?token|auth[ _-]?token|secret|password|private[ _-]?key)\s*[:=]\s*\S+/i.test(contents) || /\bsk-[A-Za-z0-9_-]{16,}\b/.test(contents)) throw new Error(`Refusing to generate ${label} because it appears to contain credential material.`); }

function privacyDraft(manifest: ShipLayerManifest): string {
  const lines = ["# App Privacy questionnaire draft", "", "> Not legal advice. Confirm each answer in App Store Connect; do not submit this draft unreviewed.", "", "## Protected-resource permissions"];
  lines.push(...(manifest.permissions.length ? manifest.permissions.map((permission) => `- **${permission.key}** — ${permission.purpose || "Purpose missing"}; confirmation: ${permission.confirmation}.`) : ["- No permissions declared. Confirm this is accurate."]));
  lines.push("", "## Data categories", ...(manifest.dataProcessing.length ? manifest.dataProcessing.map((item) => `- **${item.category}** — purposes: ${item.purpose.join(", ") || "missing"}; linked to identity: ${item.linkedToIdentity}; tracking: ${item.usedForTracking}; confirmation: ${item.confirmation}.`) : ["- No data categories declared. Confirm all collection, including processor collection."]));
  lines.push("", "## External processors", ...(manifest.externalProcessors.length ? manifest.externalProcessors.map((processor) => `- **${processor.name}** — ${processor.purpose}; data: ${processor.dataCategories.join(", ")}; confirmation: ${processor.confirmation}.`) : ["- No external processors declared. Confirm SDKs and network endpoints."]));
  return `${lines.join("\n")}\n`;
}
function complianceDraft(manifest: ShipLayerManifest): string { return `# Age rating and content-rights checklist\n\n> Draft only; not legal advice. ShipLayer never infers these declarations from source code.\n\n- Age-rating questionnaire: **${manifest.confirmations.ageRating}**. Complete the current App Store Connect questionnaire and record any regional ratings.\n- Content rights: **${manifest.confirmations.contentRights}**. Confirm whether the app contains, shows, or accesses third-party content, then make the App Store Connect declaration.\n`; }
function privacyPage(manifest: ShipLayerManifest): string {
  const app = escapeHtml(manifest.app.name || "This app"); const permissions = manifest.permissions.filter((item) => item.confirmation === "confirmed"); const processors = manifest.externalProcessors.filter((item) => item.confirmation === "confirmed");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${app} Privacy Policy</title></head><body><main><h1>${app} Privacy Policy</h1><p><strong>Draft generated by ShipLayer.</strong> Publish only after legal review and confirmation of every statement.</p><h2>Information handled by the app</h2><ul>${manifest.dataProcessing.filter((item) => item.confirmation === "confirmed").map((item) => `<li>${escapeHtml(item.category)}: used for ${escapeHtml(item.purpose.join(", ") || "the app's functionality")}.</li>`).join("") || "<li>Confirm and describe data handling before publishing.</li>"}</ul><h2>Device permissions</h2><ul>${permissions.map((item) => `<li>${escapeHtml(item.key)}: ${escapeHtml(item.purpose || "purpose to be confirmed")}.</li>`).join("") || "<li>No confirmed permissions are listed.</li>"}</ul><h2>Service providers</h2><ul>${processors.map((item) => `<li>${escapeHtml(item.name)}: ${escapeHtml(item.purpose)}.</li>`).join("") || "<li>No confirmed third-party processors are listed.</li>"}</ul><h2>Contact</h2><p>${manifest.contacts.supportEmail ? `Contact <a href="mailto:${escapeHtml(manifest.contacts.supportEmail)}">${escapeHtml(manifest.contacts.supportEmail)}</a>.` : "Add a support contact before publishing."}</p></main></body></html>`;
}
function supportPage(manifest: ShipLayerManifest): string { const app = escapeHtml(manifest.app.name || "This app"); return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${app} Support</title></head><body><main><h1>${app} Support</h1><p><strong>Draft generated by ShipLayer. Review before publishing.</strong></p><p>For help with ${app}, contact ${manifest.contacts.supportEmail ? `<a href="mailto:${escapeHtml(manifest.contacts.supportEmail)}">${escapeHtml(manifest.contacts.supportEmail)}</a>` : "the support email to be added"}.</p><h2>Purchases</h2><p>${escapeHtml(restoreText(manifest))}</p></main></body></html>`; }
function termsOfUseDraft(manifest: ShipLayerManifest): string { if (manifest.monetization.type !== "subscriptions") return "# Terms of Use / EULA\n\n> Draft only; not legal advice. This release has no declared auto-renewable subscription Terms of Use artifact.\n"; const terms = manifest.monetization.termsOfUse; return `# Terms of Use / EULA\n\n> Draft only; not legal advice. A human must confirm the App Store Connect selection and publish/review any custom terms.\n\n- Selection: **${terms.type}**\n- Confirmation: **${terms.confirmation}**\n- Public terms URL: ${manifest.monetization.termsUrl}\n\n${terms.type === "apple-standard-eula" ? "Use Apple's Standard Licensed Application End User License Agreement in App Store Connect. Verify it is appropriate for this app before submission." : "Use the public custom Terms of Use URL above only after legal review. ShipLayer does not author or validate custom legal terms."}\n`; }
export function appReviewNotes(manifest: ShipLayerManifest): string {
  const confirmedProcessors = manifest.externalProcessors.filter((processor) => processor.confirmation === "confirmed");
  const lines = [`# ${manifest.app.name || "App"} — App Review Notes`, "", "> Draft only. Verify every statement and enter actual demo credentials in App Store Connect's secure review fields, not this file.", "", "## Access", manifest.review.demoAccount?.required ? `A demo account is required. Configure the reviewer username/password in App Store Connect secure fields. ${manifest.review.demoAccount.setupInstructions || "Setup instructions are missing."}` : "No account, registration, or login is required.", "", "## Setup", ...(manifest.review.sampleData?.length ? manifest.review.sampleData.map((sample) => `- ${sample}`) : ["- Use the normal first-run flow. Add sample content as described in the recording script."]), "", "## External services", ...(confirmedProcessors.length ? confirmedProcessors.map((processor) => `- ${processor.name}: ${processor.purpose}.`) : ["- No confirmed external processors are listed. Confirm this is accurate before submission."]), "", "## Monetization", monetizationText(manifest), "", "## Recording scenarios", ...manifest.review.recordingScenarios.map((scenario, index) => `${index + 1}. ${scenario.title}: ${scenario.steps.join(" → ")}`)];
  if (manifest.review.notes) lines.push("", "## Additional notes", manifest.review.notes); return `${lines.join("\n")}\n`;
}
function recordingScript(manifest: ShipLayerManifest): string { const scenarios = manifest.review.recordingScenarios.length ? manifest.review.recordingScenarios : manifest.screenshots.scenarios; return `# Physical-device App Review recording\n\nRecord one continuous video on a physical device. Begin by launching the current submitted build. Show any permission prompt, login, paywall/purchase/restore flow, and the core workflow. Do not use a simulator recording.\n\n${scenarios.map((scenario, index) => `## ${index + 1}. ${scenario.title}\n${scenario.launchArguments?.length ? `Launch arguments: ${scenario.launchArguments.join(" ")}\n` : ""}${scenario.steps.map((step) => `- ${step}`).join("\n")}`).join("\n\n")}\n` }
function capturePlan(manifest: ShipLayerManifest): object { return { command: "shiplayer capture <repo>", prerequisites: ["macOS with Xcode for direct simulator capture", "Configured scheme and launch arguments", "No paid CI is used automatically"], configurations: manifest.screenshots.configurations.map((configuration) => ({ ...configuration, outputDirectory: `${manifest.screenshots.rawOutputDir}/${configuration.family}/${configuration.locale}`, scenarios: manifest.screenshots.scenarios.map((scenario) => ({ id: scenario.id, outputFile: `${scenario.id}.png`, title: scenario.title, launchArguments: scenario.launchArguments || [], steps: scenario.steps })) })), note: "This is a neutral hand-off. Create or use a separate app-store-screenshots scaffold/template; this JSON is not directly importable by that editor. Raw device screenshots must show the actual app and use each scenario ID as the filename." }; }
function marketingProject(manifest: ShipLayerManifest): object { return { version: 1, purpose: "Neutral hand-off plan for a separately installed app-store-screenshots editor; not an editor project file.", rawScreenshotRoot: manifest.screenshots.rawOutputDir, decks: manifest.screenshots.configurations.map((configuration) => ({ family: configuration.family, device: configuration.device, locale: configuration.locale, outputPath: `${manifest.screenshots.rawOutputDir}/${configuration.family}/${configuration.locale}/{scenario-id}.png`, slides: manifest.screenshots.scenarios.map((scenario, index) => ({ id: scenario.id, order: index, headline: scenario.title, body: scenario.steps[0] || "Describe this feature" })) })) }; }
function storeKitChecklist(manifest: ShipLayerManifest): string { const lines = ["# StoreKit / App Store Connect checklist", "", `Monetization model: **${manifest.monetization.type}**`, ""]; if (manifest.monetization.type === "free") lines.push("- No StoreKit products configured."); else if (manifest.monetization.type === "paid-app") lines.push(`- Configure paid app price point: ${manifest.monetization.pricePointReference}.`); else if (manifest.monetization.type === "non-consumables") for (const product of manifest.monetization.products) lines.push(`- Non-consumable: ${product.productId} — ${product.referenceName}; primary localization required: ${manifest.app.primaryLocale}.`); else { lines.push(`- Subscription group: ${manifest.monetization.group.referenceName}.`, `- Group localizations: ${Object.entries(manifest.monetization.group.localizations).map(([locale, copy]) => `${locale}=${copy.displayName}`).join(", ")}.`, `- Base territory: ${manifest.monetization.baseTerritory}.`, `- Paywall navigation: ${manifest.monetization.paywallNavigation}.`, `- Restore path: ${manifest.monetization.restorePath}.`); for (const product of manifest.monetization.products) lines.push(`- Level ${product.level}: ${product.productId}; ${product.duration}; intro offer: ${product.introductoryOffer ? `${product.introductoryOffer.type} ${product.introductoryOffer.duration}${product.introductoryOffer.numberOfPeriods ? ` × ${product.introductoryOffer.numberOfPeriods} periods` : ""}` : "none"}.`); } lines.push("", "Before submission, confirm StoreKit product IDs match code and App Store Connect, paywall copy displays price/duration where required, Restore Purchases works, and review screenshots/notes are attached."); return `${lines.join("\n")}\n`; }
function dryRunPlan(manifest: ShipLayerManifest): string { return `# App Store Connect dry-run plan\n\nShipLayer has not made any remote changes. A future explicit command may perform read-only discovery of:\n\n- App identity and version metadata for \`${manifest.app.bundleId || "MISSING_BUNDLE_ID"}\`\n- Localizations, build availability, screenshot sets, and App Review details\n- In-App Purchase/subscription state\n\nManual-only or human-confirmed steps remain: initial app record creation, agreements, tax/banking, trader declarations, privacy/legal declarations, asset review, and final submission.\n`; }
function humanActions(analysis: AnalysisReport, report: PreflightReport): string { const actions = [...report.results.filter((result) => result.severity !== "pass").map((result) => `${result.message}${result.remediation ? ` — ${result.remediation}` : ""}`), ...analysis.unresolvedQuestions.map((question) => `Scanner question: ${question}`), "Verify/create the App Store Connect app record and enter its ID in the manifest.", "Enter and verify metadata, URLs, contacts, copyright, category, availability, release mode, and select the uploaded build/version in App Store Connect.", "Upload and review actual App Store screenshots for every supported device family.", "Complete App Privacy, age rating, content-rights, trader, agreement, tax/banking, and legal declarations in App Store Connect.", "Verify the public Support URL contains usable contact information.", "Perform all IAP/subscription pricing, availability, localization, review-asset, paywall, restore, and disclosure setup manually where applicable.", "Make the final review submission/release decision in App Store Connect; ShipLayer v0.1 never submits it."]; return `# Remaining human actions\n\n${[...new Set(actions)].sort().map((action) => `- [ ] ${action}`).join("\n")}\n\nNever treat generated privacy/legal text as legal advice. Confirm every declaration in App Store Connect.\n`; }
function preflightMarkdown(report: PreflightReport): string { return `# ShipLayer preflight\n\n| Result | Count |\n|---|---:|\n| Pass | ${report.summary.pass} |\n| Warning | ${report.summary.warn} |\n| Blocker | ${report.summary.block} |\n\n${report.results.map((result) => `- **${result.severity.toUpperCase()}** \`${result.id}\` — ${result.message}${result.remediation ? ` _${result.remediation}_` : ""}`).join("\n")}\n`; }
function monetizationText(manifest: ShipLayerManifest): string { if (manifest.monetization.type === "free") return "No In-App Purchases or subscriptions are offered."; if (manifest.monetization.type === "paid-app") return `The app is paid at price point ${manifest.monetization.pricePointReference}.`; if (manifest.monetization.type === "non-consumables") return `Non-consumable products: ${manifest.monetization.products.map((product) => product.productId).join(", ")}. Include each product's paywall navigation and Restore Purchases path in the final notes.`; return `Auto-renewable subscription group ${manifest.monetization.group.referenceName}. Reviewer navigation: ${manifest.monetization.paywallNavigation}. Restore path: ${manifest.monetization.restorePath}.`; }
function restoreText(manifest: ShipLayerManifest): string { if (manifest.monetization.type === "free" || manifest.monetization.type === "paid-app") return "This app does not offer restorable in-app purchases."; return manifest.monetization.type === "subscriptions" ? `To restore a subscription, ${manifest.monetization.restorePath}` : `To restore a previous purchase, ${manifest.monetization.restorePath}`; }
function escapeHtml(value: string): string { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); }
