#!/usr/bin/env node
import path from "node:path";
import { existsSync } from "node:fs";
import { analyzeRepository, findValue } from "./scanner.js";
import { appStorePlan } from "./asc.js";
import { createCapturePlan, executeCapturePlan } from "./capture.js";
import { generateReleasePackage } from "./generator.js";
import { defaultManifest, manifestPath, readManifest, writeManifest } from "./manifest.js";
import { preflight } from "./preflight.js";
import { stableJson } from "./fs.js";
import type { ShipLayerManifest } from "./types.js";

const VERSION = "0.1.0";
class BlockerError extends Error {}
async function main(args: string[]): Promise<void> {
  const [command, repositoryArgument, ...options] = args;
  if (!command || command === "--help" || command === "help") return printHelp();
  if (command === "--version" || command === "version") return write(`${VERSION}\n`);
  if (!new Set(["init", "analyze", "prepare", "check", "plan", "capture", "apply", "submit"]).has(command)) throw new Error(`Unknown command '${command}'.\n\n${helpText()}`);
  if (!repositoryArgument) throw new Error(`Missing <repo>.\n\n${helpText()}`);
  const repository = path.resolve(repositoryArgument); if (!existsSync(repository)) throw new Error(`Repository does not exist: ${repository}`);
  validateOptions(command, options);
  const json = options.includes("--json");
  if (command === "init") return init(repository, options, json);
  if (command === "analyze") return analyze(repository, json);
  if (command === "prepare") return prepare(repository, options, json);
  if (command === "check") return check(repository, json, options.includes("--remote"));
  if (command === "plan") return plan(repository, json, options.includes("--remote"));
  if (command === "capture") return capture(repository, options, json);
  if (command === "apply") return apply(repository, options, json);
  if (command === "submit") return submit(repository, options, json);
  throw new Error(`Unknown command '${command}'.\n\n${helpText()}`);
}
async function init(repository: string, options: string[], json: boolean): Promise<void> { const file = manifestPath(repository); if (existsSync(file) && !options.includes("--force")) throw new Error(`${file} already exists. Refusing to overwrite it. Use --force only after reviewing the existing manifest.`); const analysis = await analyzeRepository(repository); const manifest = manifestFromAnalysis(analysis); await writeManifest(repository, manifest); output({ manifest: file, detected: analysis.findings.filter((finding) => ["bundleId", "version", "build", "deploymentTarget", "deviceFamily"].includes(finding.key)).map((finding) => ({ key: finding.key, value: finding.value, confidence: finding.confidence })), unresolvedQuestions: analysis.unresolvedQuestions }, json, `Created ${file}\n\nReview all fields marked needs-human-confirmation before running prepare.`); }
async function analyze(repository: string, json: boolean): Promise<void> { const report = await analyzeRepository(repository); output(report, json, humanAnalysis(report)); }
async function prepare(repository: string, options: string[], json: boolean): Promise<void> { const manifest = await readManifest(repository); const report = await preflight(repository, manifest); const analysis = await analyzeRepository(repository); const outputDirectory = optionValue(options, "--out") || "shiplayer-release"; const generated = await generateReleasePackage(repository, manifest, analysis, report, outputDirectory); output({ releasePackage: generated, preflight: report.summary, remainingBlockers: report.results.filter((item) => item.severity === "block") }, json, `Prepared ${generated.files.length} deterministic release artifacts in ${generated.directory}.\nPreflight: ${report.summary.pass} pass, ${report.summary.warn} warnings, ${report.summary.block} blockers.\n\nPreparation does not approve legal/privacy declarations or mutate App Store Connect.`); if (report.summary.block) process.exitCode = 2; }
async function check(repository: string, json: boolean, remote: boolean): Promise<void> { const report = await preflight(repository, await readManifest(repository), remote); output(report, json, report.results.map((item) => `${item.severity === "pass" ? "✓" : item.severity === "warn" ? "!" : "✗"} ${item.id}: ${item.message}${item.remediation ? ` (${item.remediation})` : ""}`).join("\n") + `\n\n${report.summary.pass} pass, ${report.summary.warn} warnings, ${report.summary.block} blockers.`); if (report.summary.block) process.exitCode = 2; }
async function plan(repository: string, json: boolean, remote: boolean): Promise<void> { const plan = await appStorePlan(await readManifest(repository), remote); output(plan, json, `${plan.mode === "remote" ? "Remote read/discovery plan" : "Offline dry-run plan"}\n\n${plan.operations.map((item) => `- [${item.safety}] ${item.action} ${item.resource}: ${item.description} (${item.status})`).join("\n")}\n\n${plan.warnings.map((warning) => `! ${warning}`).join("\n")}`); if (remote && !plan.credentialsPresent) process.exitCode = 2; }
async function capture(repository: string, options: string[], json: boolean): Promise<void> { const plan = await createCapturePlan(repository, await readManifest(repository)); if (options.includes("--execute")) { if (!options.includes("--yes-execute")) throw new Error("Refusing capture execution without --yes-execute. Run without --execute to inspect the missing harness requirements."); const results = await executeCapturePlan(plan); output({ plan, results }, json, "No generic capture command was run."); return; } output(plan, json, `${plan.prerequisites.map((item) => `- ${item}`).join("\n")}\n\nShipLayer v0.1 outputs a deterministic harness hand-off; it does not fabricate or execute screenshot capture.`); }
async function apply(repository: string, options: string[], json: boolean): Promise<void> { const manifest = await readManifest(repository); const report = await preflight(repository, manifest, false); const changePlan = await appStorePlan(manifest, false); if (!options.includes("--apply")) { output({ mode: "dry-run", report, plan: changePlan }, json, "DRY RUN: ShipLayer made no App Store Connect changes. Add --apply --yes-i-understand only after reviewing the plan."); return; } if (!options.includes("--yes-i-understand")) throw new Error("Production mutation gate not satisfied. Pass --apply --yes-i-understand after human review."); if (report.summary.block) throw new BlockerError("Apply blocked by preflight. Resolve every blocker before requesting production operations."); output({ mode: "manual-only", report, plan: changePlan, applied: false, unsupported: true, exitCode: 3 }, json, "UNSUPPORTED: No production mutation was made. ShipLayer v0.1 has no write adapter; complete the listed manual steps in App Store Connect."); process.exitCode = 3; }
async function submit(repository: string, options: string[], json: boolean): Promise<void> { const manifest = await readManifest(repository); const report = await preflight(repository, manifest, false); if (!options.includes("--submit") || !options.includes("--yes-submit")) { output({ mode: "final-gate-preview", report, submitted: false }, json, "FINAL GATE PREVIEW: no submission occurred. A future submission requires --submit --yes-submit and a blocker-free preflight."); return; } if (report.summary.block) throw new BlockerError("Submission blocked by preflight. Resolve every blocker before retrying."); output({ mode: "manual-only", submitted: false, unsupported: true, exitCode: 3 }, json, "UNSUPPORTED: No submission was made. ShipLayer v0.1 deliberately keeps final App Review submission human-controlled; use the generated App Store Connect plan and confirm the approved build in the UI."); process.exitCode = 3; }
function manifestFromAnalysis(report: Awaited<ReturnType<typeof analyzeRepository>>): ShipLayerManifest { const device = findValue(report, "deviceFamily"); const families: Array<"iphone" | "ipad"> = device?.includes("2") ? ["iphone", "ipad"] : ["iphone"]; const manifest = defaultManifest({ name: findValue(report, "appName") || "", bundleId: findValue(report, "bundleId") || "", version: findValue(report, "version"), build: findValue(report, "build"), deploymentTarget: findValue(report, "deploymentTarget"), deviceFamilies: families }); for (const finding of report.findings.filter((item) => item.key.startsWith("permission:"))) manifest.permissions.push({ key: finding.key.slice("permission:".length), purpose: typeof finding.value === "string" ? finding.value : undefined, confirmation: "needs-human-confirmation", evidence: finding.evidence.map((item) => item.source) }); const encryption = findValue(report, "encryption"); if (encryption === "false") manifest.build.exportCompliance = "exempt"; return manifest; }
function humanAnalysis(report: Awaited<ReturnType<typeof analyzeRepository>>): string { return `Repository: ${report.repository}\nScanned ${report.ignored.filesScanned} bounded files.\n\n${report.findings.map((finding) => `- ${finding.key}: ${Array.isArray(finding.value) ? finding.value.join(", ") : String(finding.value)} [${finding.confidence}] (${finding.evidence.map((item) => item.source).join(", ")})${finding.proposal ? " — proposal; human confirmation required" : ""}`).join("\n")}\n\nUnresolved questions:\n${report.unresolvedQuestions.map((item) => `- ${item}`).join("\n")}${report.contradictions.length ? `\n\nContradictions:\n${report.contradictions.map((item) => `- ${item}`).join("\n")}` : ""}`; }
function optionValue(options: string[], name: string): string | undefined { const index = options.indexOf(name); return index >= 0 ? options[index + 1] : undefined; }
function validateOptions(command: string, options: string[]): void { const allowed: Record<string, Set<string>> = { init: new Set(["--force", "--json"]), analyze: new Set(["--json"]), prepare: new Set(["--out", "--json"]), check: new Set(["--json", "--remote"]), plan: new Set(["--json", "--remote"]), capture: new Set(["--json", "--execute", "--yes-execute"]), apply: new Set(["--json", "--apply", "--yes-i-understand"]), submit: new Set(["--json", "--submit", "--yes-submit"]) }; const known = allowed[command]; if (!known) return; for (let index = 0; index < options.length; index++) { const option = options[index]; if (!known.has(option)) { if (command === "prepare" && index && options[index - 1] === "--out") continue; throw new Error(`Unknown option '${option}' for ${command}.`); } if (option === "--out") { const value = options[++index]; if (!value || value.startsWith("--")) throw new Error("--out requires a relative output directory."); } } }
function output(value: unknown, json: boolean, text: string): void { write(json ? stableJson(value) : `${text}\n`); }
function write(value: string): void { process.stdout.write(value); }
function printHelp(): void { write(`${helpText()}\n`); }
function helpText(): string { return `ShipLayer ${VERSION} — The missing layer between your repo and the App Store.\n\nUsage: shiplayer <command> <repo> [options]\n\nCommands:\n  init <repo> [--force]       Create shiplayer.yml from detected facts; never overwrites by default.\n  analyze <repo> [--json]     Read-only scan with evidence and unresolved questions.\n  prepare <repo> [--out DIR]  Generate a deterministic release package.\n  check <repo> [--json]       Run preflight; exits 2 for blockers.\n  plan <repo> [--remote]      Print an offline plan or read-only App Store Connect discovery.\n  capture <repo>               Print deterministic screenshot-harness hand-off requirements.\n  apply <repo> [--apply --yes-i-understand]\n                              Dry-run by default; unsupported execution exits 3.\n  submit <repo> [--submit --yes-submit]\n                              Separate final gate; unsupported execution exits 3.\n\nNo command uses paid CI or creates a GitHub Action. Secrets come only from environment-variable references.`; }
main(process.argv.slice(2)).catch((error: unknown) => { const message = error instanceof Error ? error.message : String(error); const exitCode = error instanceof BlockerError ? 2 : 1; if (process.argv.includes("--json")) process.stdout.write(`${JSON.stringify({ error: message, exitCode })}\n`); else process.stderr.write(`ShipLayer error: ${message}\n`); process.exitCode = exitCode; });
