import path from "node:path";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import type { CheckResult, PreflightReport, ShipLayerManifest } from "./types.js";
import { analyzeRepository, findValue } from "./scanner.js";
import { walkRepository } from "./fs.js";

export async function preflight(repository: string, manifest: ShipLayerManifest, remoteRequested = false): Promise<PreflightReport> {
  const results: CheckResult[] = []; const add = (id: string, severity: CheckResult["severity"], message: string, remediation?: string): void => { results.push({ id, severity, message, remediation }); };
  const app = manifest.app; if (app.name) add("app.name", "pass", "App name is present."); else add("app.name", "block", "App name is missing.", "Set app.name in shiplayer.yml.");
  if (app.bundleId) add("app.bundle-id", "pass", "Bundle ID is present."); else add("app.bundle-id", "block", "Bundle ID is missing.", "Confirm the production bundle ID.");
  if (app.appStoreAppId) add("app.store-id", "pass", "App Store Connect app ID is present."); else add("app.store-id", "warn", "App Store Connect app ID is absent; remote sync cannot target an existing app.", "Create the initial app record manually, then add app.appStoreAppId.");
  if (app.version && app.build) add("build.version", "pass", `Version ${app.version} (${app.build}) is declared.`); else add("build.version", "warn", "Version or build is missing.", "Confirm the archive version/build before upload.");
  if (manifest.contacts.supportUrl && /^https:\/\//.test(manifest.contacts.supportUrl)) add("contacts.support-url", "pass", "Support URL is present."); else add("contacts.support-url", "block", "A public HTTPS Support URL is required.", "Set contacts.supportUrl.");
  if (manifest.contacts.supportEmail) add("contacts.support-email", "pass", "Support email is present."); else add("contacts.support-email", "warn", "Support email is absent.", "Add a support email even if the public Support URL is the App Store field.");
  if (manifest.contacts.privacyUrl && /^https:\/\//.test(manifest.contacts.privacyUrl)) add("contacts.privacy-url", "pass", "Privacy policy URL is present."); else add("contacts.privacy-url", "block", "A public HTTPS Privacy Policy URL is required.", "Set contacts.privacyUrl after human/legal review.");
  if (manifest.review.contact?.email && manifest.review.contact.firstName && manifest.review.contact.lastName && manifest.review.contact.phone) add("review.contact", "pass", "App Review contact is complete."); else add("review.contact", "block", "App Review contact is incomplete.", "Set review.contact first name, last name, email, and phone.");
  if (manifest.review.demoAccount?.required && (!manifest.review.demoAccount.usernameEnv || !manifest.review.demoAccount.passwordEnv)) add("review.demo-account", "block", "Demo account is required but its environment-variable references are incomplete.", "Set usernameEnv, passwordEnv, and setup instructions; never put credentials in the manifest."); else add("review.demo-account", "pass", manifest.review.demoAccount?.required ? "Demo account uses environment-variable references." : "No login is required.");
  metadataChecks(manifest, add);
  for (const permission of manifest.permissions) { if (!permission.purpose) add(`permission.${permission.key}`, "block", `${permission.key} has no user-facing purpose string.`, "Add a specific purpose string matching the actual access."); else if (permission.confirmation !== "confirmed") add(`permission.${permission.key}`, "block", `${permission.key} is not human-confirmed.`, "Confirm this permission and its purpose before submission."); else add(`permission.${permission.key}`, "pass", `${permission.key} has a confirmed purpose string.`); }
  if (manifest.build.exportCompliance === "unknown") add("export-compliance", "block", "Export-compliance/encryption status is unknown.", "Confirm the Info.plist declaration and any required Apple documentation."); else add("export-compliance", "pass", `Export-compliance status is ${manifest.build.exportCompliance}.`);
  confirmationChecks(manifest, add); monetizationChecks(manifest, add); await screenshotChecks(repository, manifest, add); await iconChecks(repository, add); await sourceConsistencyChecks(repository, manifest, add);
  if (manifest.app.deviceFamilies.includes("iphone") && !manifest.screenshots.configurations.some((item) => item.family === "iphone")) add("screenshots.iphone", "block", "iPhone is supported but no iPhone screenshot configuration exists.", "Add a required iPhone device configuration.");
  if (manifest.app.deviceFamilies.includes("ipad") && !manifest.screenshots.configurations.some((item) => item.family === "ipad")) add("screenshots.ipad", "block", "iPad is supported but no iPad screenshot configuration exists.", "Add a required iPad device configuration.");
  if (!manifest.screenshots.scenarios.length) add("screenshots.scenarios", "block", "No screenshot/recording scenarios exist.", "Define real app-state scenarios and launch arguments."); else add("screenshots.scenarios", "pass", `${manifest.screenshots.scenarios.length} screenshot scenarios are defined.`);
  if (remoteRequested) { const required = [manifest.sync.appStoreConnectKeyIdEnv, manifest.sync.issuerIdEnv, manifest.sync.privateKeyPathEnv].filter((key): key is string => Boolean(key)); const missing = required.filter((key) => !process.env[key]); if (missing.length) add("asc.credentials", "block", `Remote App Store Connect mode is missing environment variables: ${missing.join(", ")}.`, "Set environment variables locally; do not put secrets in shiplayer.yml."); else add("asc.credentials", "pass", "Remote App Store Connect credential references are present."); }
  const summary = { pass: results.filter((item) => item.severity === "pass").length, warn: results.filter((item) => item.severity === "warn").length, block: results.filter((item) => item.severity === "block").length }; return { repository: path.resolve(repository), results, summary, canPrepare: summary.block === 0, canApply: summary.block === 0 && manifest.sync.mode === "apply", canSubmit: summary.block === 0 && manifest.confirmations.privacy === "confirmed" && manifest.confirmations.legal === "confirmed" };
}

function metadataChecks(manifest: ShipLayerManifest, add: (id: string, severity: CheckResult["severity"], message: string, remediation?: string) => void): void { const limits: Record<string, number> = { name: 30, subtitle: 30, promotionalText: 170, description: 4000, whatsNew: 4000 }; const copy = manifest.metadata.localizations[manifest.app.primaryLocale]; if (!copy?.description) add("metadata.description", "block", `Primary locale ${manifest.app.primaryLocale} has no description.`, "Add App Store description copy."); for (const [locale, values] of Object.entries(manifest.metadata.localizations)) { for (const [field, limit] of Object.entries(limits)) { const value = values[field as keyof typeof values]; if (typeof value === "string" && value.length > limit) add(`metadata.${locale}.${field}`, "block", `${locale} ${field} has ${value.length} characters; Apple limit is ${limit}.`, "Shorten the text."); } const keywords = values.keywords?.join(",") || ""; if (keywords.length > 100) add(`metadata.${locale}.keywords`, "block", `${locale} keywords have ${keywords.length} characters; Apple limit is 100.`, "Shorten keywords."); } if (copy?.description) add("metadata.description", "pass", "Primary locale description is present and within known character limits."); }
function confirmationChecks(manifest: ShipLayerManifest, add: (id: string, severity: CheckResult["severity"], message: string, remediation?: string) => void): void { for (const [key, value] of Object.entries(manifest.confirmations)) { if (value === "confirmed" || value === "not-applicable") add(`confirmation.${key}`, "pass", `${key} declaration is ${value}.`); else add(`confirmation.${key}`, "block", `${key} declaration requires explicit human confirmation.`, "Confirm only after reviewing the relevant App Store Connect/legal requirement."); } for (const item of [...manifest.dataProcessing, ...manifest.externalProcessors]) if (item.confirmation !== "confirmed" && item.confirmation !== "not-applicable") { const name = "name" in item ? item.name : item.category; add(`privacy.${name}`, "block", `${name} requires human privacy confirmation.`, "Confirm collection, use, tracking, identity linkage, and third-party processing."); } }
function monetizationChecks(manifest: ShipLayerManifest, add: (id: string, severity: CheckResult["severity"], message: string, remediation?: string) => void): void { const money = manifest.monetization; if (money.type === "free") { add("monetization", "pass", "Free app with no declared IAP." ); return; } if (money.type === "paid-app") { add("monetization", money.pricePointReference ? "pass" : "block", "Paid app price point is declared."); return; } if (money.type === "non-consumables") { if (!money.products.length) add("iap.products", "block", "At least one non-consumable product is required."); for (const product of money.products) { const primary = product.localizations[manifest.app.primaryLocale]; if (!primary?.displayName || !primary.description) add(`iap.${product.productId}.localization`, "block", `${product.productId} lacks primary localization.`, "Add display name and description."); if (!product.reviewScreenshot) add(`iap.${product.productId}.review-screenshot`, "warn", `${product.productId} has no App Review screenshot.`, "Provide review assets before submission."); } return; } if (money.confirmation !== "confirmed") add("subscriptions.confirmation", "block", "Subscription model needs human confirmation.", "Confirm App Store subscription requirements, terms, and pricing."); if (!money.products.length) add("subscriptions.products", "block", "Subscription group has no products."); for (const product of money.products) { if (!product.pricePointReference) add(`subscription.${product.productId}.price`, "block", `${product.productId} has no price point reference.`); if (!product.reviewScreenshot) add(`subscription.${product.productId}.review-screenshot`, "warn", `${product.productId} has no App Review screenshot.`); } add("subscriptions.restore", money.restorePath ? "pass" : "block", "Subscription restore path is declared."); }
async function screenshotChecks(repository: string, manifest: ShipLayerManifest, add: (id: string, severity: CheckResult["severity"], message: string, remediation?: string) => void): Promise<void> { for (const config of manifest.screenshots.configurations) { const directory = path.resolve(repository, manifest.screenshots.rawOutputDir, config.family, config.locale); if (!existsSync(directory)) { add(`screenshots.${config.family}.${config.locale}`, "warn", `Screenshot directory does not exist yet: ${path.relative(repository, directory)}.`, "Run capture or place actual screenshots there."); continue; } const files = (await import("node:fs/promises")).readdir(directory); const imageFiles = (await files).filter((file) => /\.(png|jpe?g)$/i.test(file)); if (!imageFiles.length) { add(`screenshots.${config.family}.${config.locale}`, "block", `No PNG/JPEG screenshots found for ${config.family}/${config.locale}.`, "Capture at least one actual app screenshot."); continue; } if (imageFiles.length > 10) add(`screenshots.${config.family}.${config.locale}.count`, "warn", `${imageFiles.length} screenshots found; App Store allows up to 10.`); else add(`screenshots.${config.family}.${config.locale}.count`, "pass", `${imageFiles.length} screenshot(s) found.`); for (const image of imageFiles) { const details = await imageDetails(path.join(directory, image)); if (!details) { add(`screenshot.${image}`, "warn", `Could not inspect ${image}; verify dimensions and alpha manually.`); continue; } if (details.width !== config.requiredDimensions.width || details.height !== config.requiredDimensions.height) add(`screenshot.${image}.dimensions`, "warn", `${image} is ${details.width}×${details.height}; config requests ${config.requiredDimensions.width}×${config.requiredDimensions.height}.`, "Use an Apple-accepted size for this display class."); else add(`screenshot.${image}.dimensions`, "pass", `${image} matches configured dimensions.`); if (details.alpha) add(`screenshot.${image}.alpha`, "block", `${image} has an alpha channel.`, "Export a flattened PNG/JPEG without transparency."); } } }
async function iconChecks(repository: string, add: (id: string, severity: CheckResult["severity"], message: string, remediation?: string) => void): Promise<void> { const files = (await walkRepository(repository)).files; const iconCatalog = files.find((file) => file.endsWith("AppIcon.appiconset/Contents.json")); if (!iconCatalog) { add("assets.app-icon", "block", "No AppIcon.appiconset was found.", "Add the app icon asset catalog."); return; } add("assets.app-icon", "pass", `App icon asset catalog found at ${path.relative(repository, iconCatalog)}.`); const folder = path.dirname(iconCatalog); if (!files.some((file) => path.dirname(file) === folder && /\.(png|jpe?g)$/i.test(file))) add("assets.app-icon-images", "warn", "The AppIcon asset catalog has no raster image files in the scanned repository.", "Verify generated/compiled app icon assets before upload."); }
async function sourceConsistencyChecks(repository: string, manifest: ShipLayerManifest, add: (id: string, severity: CheckResult["severity"], message: string, remediation?: string) => void): Promise<void> { const report = await analyzeRepository(repository); const compare = (key: "bundleId" | "version" | "build", expected: string | undefined): void => { const detected = findValue(report, key); if (!expected || !detected) return; if (expected === detected) add(`consistency.${key}`, "pass", `Manifest ${key} matches source evidence.`); else add(`consistency.${key}`, "block", `Manifest ${key} (${expected}) disagrees with source evidence (${detected}).`, "Update the manifest or archive/project setting."); }; compare("bundleId", manifest.app.bundleId); compare("version", manifest.app.version); compare("build", manifest.app.build); }
async function imageDetails(filePath: string): Promise<{ width: number; height: number; alpha: boolean } | undefined> { const buffer = await readFile(filePath); if (buffer.subarray(1, 4).toString() === "PNG") return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20), alpha: [4, 6].includes(buffer[25]) }; if (buffer[0] === 0xff && buffer[1] === 0xd8) { for (let index = 2; index < buffer.length - 9; index++) if (buffer[index] === 0xff && [0xc0, 0xc1, 0xc2].includes(buffer[index + 1])) return { height: buffer.readUInt16BE(index + 5), width: buffer.readUInt16BE(index + 7), alpha: false }; } return undefined; }
